---
common:
  disable_legacy_facts: true

Gemfile:
  optional:
    ':development':
      - gem: puppet-resource_api

spec/spec_helper.rb:
  mock_with: ':rspec'
  strict_level: ':error'

.rubocop.yml:
  default_configs:
    AllCops:
      # 2.4 is the newest that's working right now with PDK 1.18.1.
      TargetRubyVersion: 2.4

.travis.yml:
  dist: focal

.vscode/extensions.json:
  delete: true
