---
common:
  disable_legacy_facts: true

Gemfile:
  optional:
    ':development':
      - gem: puppet-resource_api
      - gem: github_changelog_generator
      - gem: dnsruby

.pdkignore:
  paths:
    - /run_tests

Rakefile:
  changelog_user: kenyon

spec/spec_helper.rb:
  mock_with: ':rspec'
  strict_level: ':error'

.travis.yml:
  dist: focal

.vscode/extensions.json:
  delete: true
