name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate_and_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-pdk
      - run: pdk validate --parallel
      - run: pdk test unit --parallel

  acceptance_bind_spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-pdk
      - uses: ./.github/actions/acceptance-test
        with:
          filename: bind_spec

  acceptance_bind_backport_spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-pdk
      - uses: ./.github/actions/acceptance-test
        with:
          filename: bind_backport_spec

  acceptance_bind_resolvconf_service_spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-pdk
      - uses: ./.github/actions/acceptance-test
        with:
          filename: bind_resolvconf_service_spec

  acceptance_bind_authoritative_spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-pdk
      - uses: ./.github/actions/acceptance-test
        with:
          filename: bind_authoritative_spec
