name: Build and publish release to Puppet Forge

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get pushed tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}
      - name: Build and publish module
        uses: barnumbirr/action-forge-publish@b540819fa37ed3e40eb6c01807fe57721c128a42
        env:
          FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}
          REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
